site_name: Grace Hopper

repo_url: https://github.com/FCTE-Qualidade-de-Software-1/2025-2_T01_GRACE_HOPPER

nav:
  - Home: index.md
  - Fase:
    - Fase 1:
      - Apresentação: fase1/apresentacao.md
      - Stakeholders: fase1/stakeholders.md
      - Tipo de Produto: fase1/tipo_produto.md
      - Modelo de Qualidade: fase1/modelo_qualidade.md
      - Características: fase1/caracteristicas.md
      - Escopo: fase1/escopo.md
      - ODS: fase1/ods.md
    - Fase 2: fase2.md
    - Fase 3: fase3.md
    - Fase 4: fase4.md

theme:
  name: material    
  font:
    text: Roboto
    code: Roboto Mono
  language: pt-BR
  features:
    - navigation.top         
    - navigation.sections    
    - toc.integrate         
    - content.code.copy      
    - content.code.annotate
    - content.code.copy
    - content.code.fold
    - content.tabs.link
    
  
  palette:
    scheme: default
    accent: indigo
    primary: indigo

extra:
  generator: false
    
