site_name: Projeto Grace Hopper
site_url: https://fcte-qualidade-de-software-1.github.io/2025-2_T01_GRACE_HOPPER/
docs_dir: docs
repo_url: https://github.com/FCTE-Qualidade-de-Software-1/2025-2_T01_GRACE_HOPPER
repo_name: FCTE-Qualidade-de-Software-1/2025-2_T01_GRACE_HOPPER

theme:
  name: material
  palette:
    scheme: default
    toggle:
      icon: material/toggle-switch
      name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - navigation.tracking
    - navigation.search.highlight
    - navigation.search.suggest
    - navigation.search.share
    - navigation.search.highlight
    - navigation.search.suggest
    - navigation.search.share
    - toc.integrate

nav:
  - Home: index.md
  - Fases:
      - Fase 01: fases/fases01.md
      - Fase 02: fases/fases02.md
      - Fase 03: fases/fases03.md
      - Fase 04: fases/fases04.md
