site_name: Grace Hopper

repo_url: https://github.com/FCTE-Qualidade-de-Software-1/2025-2_T01_GRACE_HOPPER

nav:
  - Home: index.md
  - Fase:
    - Fase 1:
      - Apresentação: fase1/apresentacao.md
      - Stakeholders: fase1/stakeholders.md
      - Tipo de Produto: fase1/tipo_produto.md
      - Modelo de Qualidade: fase1/modelo_qualidade.md
      - Características: fase1/caracteristicas.md
      - Escopo: fase1/escopo.md
      - ODS: fase1/ods.md
    - Fase 2: fase2.md
    - Fase 3: fase3.md
    - Fase 4: fase4.md

theme:
  name: material    
  font:
    text: Roboto
    code: Roboto Mono
  language: pt-BR
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: teal

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: teal
    - scheme: high-contrast
      primary: black
      accent: yellow
      toggle:
        icon: material/weather-cloudy-alert
        name: Switch to high contrast

extra:
  generator: false
    
