site_name: Projeto Grace Hopper
site_url: https://fcte-qualidade-de-software-1.github.io/2025-2_T01_GRACE_HOPPER/
docs_dir: docs
repo_url: https://github.com/FCTE-Qualidade-de-Software-1/2025-2_T01_GRACE_HOPPER
repo_name: FCTE-Qualidade-de-Software-1/2025-2_T01_GRACE_HOPPER
nav:
  - Home: index.md
  - Fases:
      - Fase 01: fases/fases01.md
      - Fase 02: fases/fases02.md
      - Fase 03: fases/fases03.md
      - Fase 04: fases/fases04.md
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/mathjax.js
theme:
  name: material
plugins:
  - minify
